### ISSUE TITLE
Instructions unclear, unable to use

### ISSUE THREAD

**Issue by jadenquinn** [Otttter/Group-Leaver#6]
I got group botted last night and I'm trying to alleviate that, and telling me "if you don't know how to do THIS, you probably shouldn't be using this script" Well, it's not a choice I can make, I don't have the time to leave 2,000+ DM groups. Make better instructions.
Google results don't give me any usable instructions for getting my Discord token, I assume either Chrome or Discord updated after these pages I went to were made, so I have no idea how to get my token. Could you give me actual instructions, or better yet, put them in your README? Thanks.

Here's the error I get: 
C:\Users\Jaden\Downloads\Release>"Group Leaver.exe"
Traceback (most recent call last):
  File "discord\http.py", line 300, in static_login
  File "discord\http.py", line 254, in request
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "groupleaver-exec.py", line 42, in <module>
  File "discord\client.py", line 723, in run
  File "discord\client.py", line 702, in runner
  File "discord\client.py", line 665, in start
  File "discord\client.py", line 511, in login
  File "discord\http.py", line 304, in static_login
discord.errors.LoginFailure: Improper token has been passed.
[11996] Failed to execute script 'groupleaver-exec' due to unhandled exception!
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002633CFD7E20>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 116, in __del__
  File "asyncio\proactor_events.py", line 108, in close
  File "asyncio\base_events.py", line 745, in call_soon
  File "asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed

C:\Users\Jaden\Downloads\Release>

**Comment by jadenquinn** [comment]
Alright I finally got it working, got my token, but the script is overloading Discord. It does like 10 groups and then craps out because it's going to fast or something.

**Comment by jadenquinn** [comment]
Token Verification Successful! Type #gl in to any chat and the script will execute!
Left a group: 1222611108485926932
Left a group: 1222613606969905282
Left a group: 1222613608404353136
Left a group: 1222613611068002324
Left a group: 1222613613353631918
Left a group: 1222613615287210065
Left a group: 1222613618433069146
Left a group: 1222613620949782538
Left a group: 1222613622380036138
Ignoring exception in on_message
Traceback (most recent call last):
  File "discord\client.py", line 343, in _run_event
  File "groupleaver-exec.py", line 36, in on_message
  File "discord\abc.py", line 1065, in send
  File "discord\http.py", line 267, in request
discord.errors.HTTPException: 429 Too Many Requests (error code: 20028): The write action you are performing on the channel has hit the write rate limit.
Press enter to exit
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001F3447B7C70>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 116, in __del__
  File "asyncio\proactor_events.py", line 108, in close
  File "asyncio\base_events.py", line 745, in call_soon
  File "asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed

C:\Users\Jaden\Downloads\Release>"Group Leaver.exe"




This might actually be worse than doing leaving them manually.

**Comment by jadenquinn** [comment]
You need to introduce some kind of delay. Maybe configurable. You also should start with the most recent groups first, obviously. I ran this script and it slowly churned through all of my years old DM groups for no good reason, say goodbye to those forever I guess.

**Comment by Otttter** [comment]
I'm in no way shape or form responsible for your inability to understand what this 38 line python script does. This tool was written 5 years ago back when self botting was actually feasible. If you had researched the issue properly you would understand why. The script is designed to leave ALL groups not just random ones. There is a built in feature that allows you to send the command inside ONE group chat which essentially adds it to a "whitelist" and prevents the script from including it in the mass deletion queue. This is very clearly discernable by the code that is publicly available in the repo.

I don't explain how to get your token because when I released this script, it was a completely different process. As exciting as keeping up with random discord shit everyday sounds, I unfortunately have more important things to deal with. I update this based on if I feel like it, not because I have to.

You didn't pay a dime for this, I am under no obligation to "fix" anything nor do I really care about this anymore. The first release was 2019. Discord's API has changed so much since then, which you would know if you knew how/what the proper way to get your token, or any server-side discord information was.

Instead of randomly downloading scripts you don't know how to read you should probably learn how to read the code before running it.

**Comment by jadenquinn** [comment]
> I'm in no way shape or form responsible for your inability to understand what this 38 line python script does. This tool was written 5 years ago back when self botting was actually feasible. If you had researched the issue properly you would understand why. The script is designed to leave ALL groups not just random ones. There is a built in feature that allows you to send the command inside ONE group chat which essentially adds it to a "whitelist" and prevents the script from including it in the mass deletion queue. This is very clearly discernable by the code that is publicly available in the repo.
> 
> 
> 
> I don't explain how to get your token because when I released this script, it was a completely different process. As exciting as keeping up with random discord shit everyday sounds, I unfortunately have more important things to deal with. I update this based on if I feel like it, not because I have to.
> 
> 
> 
> You didn't pay a dime for this, I am under no obligation to "fix" anything nor do I really care about this anymore. The first release was 2019. Discord's API has changed so much since then, which you would know if you knew how/what the proper way to get your token, or any server-side discord information was.
> 
> 
> 
> Instead of randomly downloading scripts you don't know how to read you should probably learn how to read the code before running it.

Instead of critiquing your users, fix the issues with your script. I have no dev experience, you can't assume I know jack about how it works, I just needed SOMETHING that worked.

**Comment by jadenquinn** [comment]
...wow.. someone had a bad day at work..

**Comment by Otttter** [comment]
![image](https://github.com/user-attachments/assets/176ee3f5-193a-4594-ad95-bb8344365823)
Someone has shitty friends 🤷 it's very hard to see why you got botted... Oh sorry let me throw a few more in . . . . . . . . . . .     . .     .  . .    .   .  .  .  . .
