### ISSUE TITLE
Instructions unclear, unable to use

### ISSUE THREAD

**Issue by Daamss** [Otttter/Group-Leaver#7]
hey man im having this issue with ur bot. Not really the bot, but more the github itself. I noticed that you have an idiot making issue requests about stupid shit he can't figure out and idk how to get rid of it. Is it a bug? a feature? I'm getting scared.... please update your code so i can read it properly and get rid of this garbage. attached is a picture of what im talking about i think idk

**Comment by Daamss** [comment]
![idiot](https://github.com/Otttter/Group-Leaver/assets/33853471/f6198b46-0a40-4db0-acf8-47b9c4030221)

**Comment by Otttter** [comment]
Absolutely boggling what mf's be doin these days. I know I'd never run random shit on github without proof reading it first. Not even github is immune from malware

**Comment by Daamss** [comment]
fixed
